services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: appointment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appointment_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:6-alpine
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      TELEGRAM_BOT_TOKEN: "7119840176:AAFGBwRj3_CUueg9g6MnqpWkJvedTfabPl8"  # Убрал дефис и добавил кавычки
      TELEGRAM_CHAT_ID: "962583970"  # Убрал дефис и добавил кавычки
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "appointment_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
  redis_data: